use cairo_lang_defs::db::DefsGroup;
use cairo_lang_defs::ids::TopLevelLanguageElementId;
use cairo_lang_test_utils::parse_test_file::TestRunnerResult;
use cairo_lang_test_utils::verify_diagnostics_expectation;
use cairo_lang_utils::ordered_hash_map::OrderedHashMap;

use crate::items::macro_call::module_macro_modules;
use crate::test_utils::{SemanticDatabaseForTesting, setup_test_module};

cairo_lang_test_utils::test_file_test!(
    full_paths,
    "src/items/tests",
    {
        macro_call: "macro_call",
    },
    test_macro_call_item_full_paths,
    ["expect_diagnostics"]
);

/// Prints the full paths of all free functions in the module, including those defined inside
/// modules generated by item-level inline macro calls.
fn test_macro_call_item_full_paths(
    inputs: &OrderedHashMap<String, String>,
    args: &OrderedHashMap<String, String>,
) -> TestRunnerResult {
    let db = &SemanticDatabaseForTesting::default();
    let (test_module, diagnostics) = setup_test_module(db, &inputs["module_code"]).split();
    let mut paths = vec![];
    for module_id in module_macro_modules(db, true, test_module.module_id).iter().copied() {
        for free_function_id in db.module_free_functions_ids(module_id).unwrap() {
            paths.push(free_function_id.full_path(db));
        }
    }
    let error = verify_diagnostics_expectation(args, &diagnostics);
    TestRunnerResult {
        outputs: OrderedHashMap::from([
            ("free_function_full_paths".into(), paths.join("\n")),
            ("expected_diagnostics".into(), diagnostics),
        ]),
        error,
    }
}
