= Expression statement

An _expression statement_ evaluates an xref:expressions.adoc[expression] and ignores its result.
Its purpose is to trigger side effects of expression evaluation only.

When an expression that ends with a block (i.e. '}') is used in a context where a statement is
permitted, the trailing semicolon can be omitted without changing the semantic meaning.
This is different from omitting the semicolon after a non-block expression.
This can include xref:if-expressions.adoc[if], xref:match-expressions.adoc[match], xref:for-loop-expressions.adoc[for], etc.
This can cause an ambiguity between it being parsed as a standalone statement and as a part of
another expression; in this case, it is parsed as a statement.

[source,cairo]
----
v.pop_front();    // Ignore the element returned from pop_front
if v.is_empty() {
    v.append(5);
} else {
    v.pop_front();  // Remove the first element
}                 // Semicolon can be omitted.
[1];              // Separate expression statement, not an indexing expression
----

When the trailing semicolon is omitted, the result return type of the expression must be
the xref:unit-type.adoc[unit type].

[source,cairo]
----
// bad: the block's type is i32, not ()
// Error: expected `()` because of default return type
// if true {
//   1_i32
// }

// good: the block's type is i32
if true {
  1_i32
} else {
  2_i32
};
----
