/// Configuration for contract deployment
///
/// This structure contains parameters needed to deploy a new contract instance
/// Used by the typed deployment function generated by the Starknet Cairo plugin.
#[cfg(target: 'test')]
#[derive(Drop, Copy, Debug, PartialEq, Serde, Default)]
pub struct DeploymentParams {
    /// The salt, an arbitrary value provided by the deployer, used in the computation of the
    /// contract's address.
    pub salt: felt252,
    /// Deploy the contract from the zero address.
    pub deploy_from_zero: bool,
}
