//! Generated compile-time canary scenarios.
//!
//! Each canary is a small generated single-file project shaped to make a specific class of
//! super-linear compilation cost show up as a step change on the benchmark dashboard: large
//! array literals, structs with many members, enums with many variants, deeply nested
//! struct/enum types, and many nested loops. Real projects hit all of these shapes (e.g.
//! embedded test vectors, generated bindings), so compilation should stay roughly linear in
//! each dimension.
//!
//! The sources are generated at benchmark time rather than checked in, so each canary's size
//! is a one-line tweak. Control flow after the heavy construct is intentional: it forces
//! per-block compiler state to be carried across edges, as happens wherever real code consumes
//! the value.

use std::path::Path;

use super::BenchConfig;

/// Number of elements in the `big_array` canary's array literal.
const BIG_ARRAY_ELEMENTS: usize = 2000;
/// Number of members in the `large_struct` canary's struct.
const LARGE_STRUCT_MEMBERS: usize = 512;
/// Number of variants in the `wide_enum` canary's enum.
const WIDE_ENUM_VARIANTS: usize = 256;
/// Nesting depth (struct/enum pairs) of the `deep_nesting` canary's type chain.
const DEEP_NESTING_DEPTH: usize = 64;
/// Number of loop-nest functions in the `nested_loops` canary.
const NESTED_LOOPS_FUNCTIONS: usize = 24;
/// Loop nesting depth within each `nested_loops` function.
const NESTED_LOOPS_DEPTH: usize = 4;

/// Writes each canary's source file under `dir` and returns their [`BenchConfig`]s.
pub fn canary_configs(dir: &Path) -> Vec<BenchConfig> {
    std::fs::create_dir_all(dir)
        .unwrap_or_else(|e| panic!("failed to create {}: {e}", dir.display()));
    let canaries: [(&'static str, String); 5] = [
        ("big_array", big_array()),
        ("large_struct", large_struct()),
        ("wide_enum", wide_enum()),
        ("deep_nesting", deep_nesting()),
        ("nested_loops", nested_loops()),
    ];
    canaries
        .into_iter()
        .map(|(name, content)| {
            let path = dir.join(format!("{name}.cairo"));
            let content =
                format!("// Generated by the compile benchmark; see canaries.rs.\n{content}");
            std::fs::write(&path, content)
                .unwrap_or_else(|e| panic!("failed to write {}: {e}", path.display()));
            BenchConfig { name, path, starknet: false, sierra_phases: true, main_crate: None }
        })
        .collect()
}

/// A single function building a `BIG_ARRAY_ELEMENTS`-long `array![...]` literal, then asserting
/// on and popping it. Guards costs that scale super-linearly with an array literal's length
/// (e.g. per-append state in lowering analyses).
fn big_array() -> String {
    let elements = (0..BIG_ARRAY_ELEMENTS).map(|i| i.to_string()).collect::<Vec<_>>().join(", ");
    format!(
        "pub fn big_array() -> Array<felt252> {{
    let mut arr = array![{elements}];
    assert!(arr.len() == {BIG_ARRAY_ELEMENTS}, \"wrong len\");
    let first = arr.pop_front();
    assert!(first == Some(0), \"wrong first\");
    arr
}}
"
    )
}

/// A struct with `LARGE_STRUCT_MEMBERS` members: constructed, member-accessed, destructured and
/// re-aggregated. Guards costs that scale super-linearly with a struct's member count.
fn large_struct() -> String {
    let n = LARGE_STRUCT_MEMBERS;
    let members = (0..n).map(|i| format!("    m{i}: felt252,")).collect::<Vec<_>>().join("\n");
    let init = (0..n).map(|i| format!("m{i}: {i}")).collect::<Vec<_>>().join(", ");
    let bindings = (0..n).map(|i| format!("m{i}")).collect::<Vec<_>>().join(", ");
    // Sum in chunks to keep expression trees shallow; the goal is many member uses, not one
    // deep expression.
    let chunk_sums = (0..n / 32)
        .map(|c| {
            let terms =
                (c * 32..(c + 1) * 32).map(|i| format!("m{i}")).collect::<Vec<_>>().join(" + ");
            format!("    let sum{c} = {terms};")
        })
        .collect::<Vec<_>>()
        .join("\n");
    let total = (0..n / 32).map(|c| format!("sum{c}")).collect::<Vec<_>>().join(" + ");
    let expected = n * (n - 1) / 2;
    format!(
        "#[derive(Copy, Drop)]
struct Big {{
{members}
}}

pub fn large_struct() -> felt252 {{
    let s = Big {{ {init} }};
    assert!(s.m0 == 0, \"bad first\");
    assert!(s.m{last} == {last}, \"bad last\");
    let Big {{ {bindings} }} = s;
{chunk_sums}
    let total = {total};
    assert!(total == {expected}, \"bad sum\");
    total
}}
",
        last = n - 1,
    )
}

/// An enum with `WIDE_ENUM_VARIANTS` variants and a full match over it. Guards costs that scale
/// super-linearly with an enum's variant count (construction, matching, and match optimization).
fn wide_enum() -> String {
    let n = WIDE_ENUM_VARIANTS;
    let variants = (0..n).map(|i| format!("    V{i}: felt252,")).collect::<Vec<_>>().join("\n");
    let arms =
        (0..n).map(|i| format!("        Wide::V{i}(x) => x + {i},")).collect::<Vec<_>>().join("\n");
    let last = n - 1;
    format!(
        "#[derive(Copy, Drop)]
enum Wide {{
{variants}
}}

fn classify(w: Wide) -> felt252 {{
    match w {{
{arms}
    }}
}}

pub fn wide_enum() -> felt252 {{
    let a = classify(Wide::V0(1));
    let b = classify(Wide::V{mid}(2));
    let c = classify(Wide::V{last}(3));
    assert!(a + b + c == {expected}, \"bad sum\");
    a + b + c
}}
",
        mid = n / 2,
        expected = (1) + (2 + n / 2) + (3 + last),
    )
}

/// A chain of `DEEP_NESTING_DEPTH` alternating struct/enum types, with one expression building
/// the full tower and a match pyramid unwrapping it back down. Guards costs that scale
/// super-linearly with type nesting depth.
fn deep_nesting() -> String {
    let d = DEEP_NESTING_DEPTH;
    let mut types = vec![
        "#[derive(Copy, Drop)]\nstruct S0 {\n    x: felt252,\n}".to_string(),
        "#[derive(Copy, Drop)]\nenum E0 {\n    A: S0,\n    B: S0,\n}".to_string(),
    ];
    for k in 1..d {
        types.push(format!(
            "#[derive(Copy, Drop)]\nstruct S{k} {{\n    x: E{prev},\n    y: felt252,\n}}",
            prev = k - 1
        ));
        types.push(format!("#[derive(Copy, Drop)]\nenum E{k} {{\n    A: S{k},\n    B: S{k},\n}}"));
    }
    // The tower literal: E{d-1}::A(S{d-1} { x: E{d-2}::A(...), y: d-1 }).
    let mut literal = "S0 { x: 7 }".to_string();
    literal = format!("E0::A({literal})");
    for k in 1..d {
        literal = format!("E{k}::A(S{k} {{ x: {literal}, y: {k} }})");
    }
    // The match pyramid: unwrap each enum level, descending into the struct's `x` member.
    // unwrap(k) over an expression of type E{k}; the base case reads S0's payload.
    fn unwrap(k: usize, expr: &str) -> String {
        if k == 0 {
            format!("match {expr} {{ E0::A(s0) => s0.x, E0::B(_) => 0 }}")
        } else {
            let inner = unwrap(k - 1, &format!("s{k}.x"));
            format!("match {expr} {{ E{k}::A(s{k}) => {inner}, E{k}::B(_) => 0 }}")
        }
    }
    let pyramid = unwrap(d - 1, "v");
    let types = types.join("\n\n");
    format!(
        "{types}

pub fn deep_nesting() -> felt252 {{
    let v = {literal};
    let leaf = {pyramid};
    assert!(leaf == 7, \"bad leaf\");
    leaf
}}
"
    )
}

/// `NESTED_LOOPS_FUNCTIONS` functions, each containing a `NESTED_LOOPS_DEPTH`-deep nest of
/// short loops, summed by a root function. Guards costs that scale super-linearly with the
/// number/nesting of loops (each loop lowers into its own function).
fn nested_loops() -> String {
    let mut out = String::new();
    for f in 0..NESTED_LOOPS_FUNCTIONS {
        let mut body = "acc += 1;".to_string();
        for level in (0..NESTED_LOOPS_DEPTH).rev() {
            let indent = "    ".repeat(NESTED_LOOPS_DEPTH - level);
            body = format!(
                "let mut i{level} = 0;
{indent}loop {{
{indent}    if i{level} == 2 {{
{indent}        break;
{indent}    }}
{indent}    {body}
{indent}    i{level} += 1;
{indent}}};"
            );
        }
        out.push_str(&format!(
            "fn nest{f}() -> felt252 {{
    let mut acc = 0;
    {body}
    acc
}}

"
        ));
    }
    let total: String =
        (0..NESTED_LOOPS_FUNCTIONS).map(|f| format!("nest{f}()")).collect::<Vec<_>>().join(" + ");
    let expected = NESTED_LOOPS_FUNCTIONS * 2usize.pow(NESTED_LOOPS_DEPTH as u32);
    out.push_str(&format!(
        "pub fn nested_loops() -> felt252 {{
    let total = {total};
    assert!(total == {expected}, \"bad total\");
    total
}}
"
    ));
    out
}
