= Literal expressions

[source,bnf]
----
LITERAL_EXPR : NUMERIC_LITERAL
             | BOOLEAN_LITERAL
----

A _literal expression_ is an expression consisting of a single token, rather than a sequence of
tokens, that immediately and directly denotes the value it evaluates to, rather than referring to it
by name or some other evaluation rule.

== Boolean literals

[source,bnf]
----
BOOLEAN_LITERAL : "true" | "false"
----

The two values of the boolean type are written `true` and `false`.

== Numeric literals

[source,bnf]
----
NUMERIC_LITERAL : ( DEC_LITERAL | HEX_LITERAL | BIN_LITERAL ) LITERAL_SUFFIX?

DEC_LITERAL : [0-9] [0-9_]*
HEX_LITERAL : "0x" [a-fA-F0-9_]*
BIN_LITERAL : "0b" [01_]*

LITERAL_SUFFIX : XID_Start XID_Continue*
----

A numeric literal can be written using three bases:

1. A decimal literal consists of only decimal digits.
2. A hexadecimal literal starts with the character sequence `0x` and continues with hex digits.
3. A binary literal starts with the character sequence `0b` and continues with binary digits.

A numeric literal may be followed (immediately, without any spaces) by an underscore character (`_`)
and then a __literal suffix__, which forcibly sets the type of the literal.
The literal suffix is any valid identifier, but only selected values are semantically correct.

> **Note**: Floating-point numbers are not supported.

Examples of numeric literals of various forms:

[cols="1,1,1",options="header"]
|===
| Literal                 | Value | Type
| `1234`                  | 1234  | `felt252`
| `1234_felt252           | 1234  | `felt252`
| `1234_i32               | 1234  | `i32`
| `1234_u128              | 1234  | `u128`
| `0x4D2`                 | 1234  | `felt252`
| `0b0000010011010010`    | 1234  | `felt252`
|===

Examples of invalid numeric literals:

- Invalid suffix: +
  `1234suffix`
- Use of digits of wrong base: +
  `123AFB43`, `0b0102`, `0o0581`, `0xG`.
- Binary and hexadecimal literals must have at least one digit: +
  `0b`, `0x_u128`

> **Note:** Cairo syntax considers `-1` as an application of
> the link:negation-operators.adoc[unary minus operator] to the numeric literal `1`, rather than a
> single numeric literal.
