= Cairo Traits and Impls

Cairo traits and impls are a feature of the Cairo language, providing a way to define
abstract behavior and implement it in a concrete manner.
Traits define a set of related functions, while impls provide the actual implementation of those
functions. This feature promotes code reusability and modular design.

== Example:

[source,rust]
----
trait Display<T> {
    fn display(x: T) -> Array<u8>;
}

impl DisplayUsize of Display<usize> {
    fn display(x: usize) -> Array<u8> {
        ...
    }
}

fn main() {
    // Can be called by the trait name.
    let a = Display::display(5_usize);
    // Can be called by the impl name.
    let b = DisplayUsize::display(5_usize);
    // Cannot be called by the type name.
    // T::display(value) - Does not work.
}
----

Note that unlike Rust, impls have names, so that they can be explicitly specified.

== Impls as generic parameters
In Cairo, impls can be used as generic parameters, allowing for a more flexible and modular design.
For example, the following code defines a function that takes a generic parameter `T` and
an implementation of the `Display<T>` trait:
[source,rust]
----
fn foo<T, impl TDisplay: Display<T>>(value: T) {
    let a = TDisplay::display(5_usize);
    let b = Display::display(value);
}
----

== Search locations for impl
When a trait function is called, the compiler will search for the impl in the following locations:
* Defined generic parameters in the current scope.
* The current module.
* The core module.
* Defining module of each of the generic arguments of the trait. For example, the impl for
`Display<usize>` will be searched for in the module where `usize` is defined.

== Multiple impls and ambiguity
When searching for an impl, and multiple results are found for the same concrete trait (e.g.
`Display<usize>`), the compiler will throw an error. This is to prevent ambiguity in the code. In
this case, the user must specify the impl name explicitly.

== `self` and Methods
The self parameter in Cairo trait and impl functions represents a value of a specified type,
allowing for a more convenient method-like syntax for that type. It must be the first parameter of
the function. A function defined in such a way can be called as a method on the value:

[source,rust]
----
trait Display<T> {
    fn display(self: T) -> Array<u8>;
}

impl DisplayUsize of Display<usize> {
    fn display(self: usize) -> Array<u8> {
        ...
    }
}

fn bar<T: impl TDisplay: Display<T>>(value: T) {
    ...
    // Can be called as a method.
    let c = value.display();
    ...
}
----

== Search locations for methods.
When a method is called, the compiler will search for a trait containing a function with a matching
name in the current scope.
For each matching trait, it will search for an impl (as specified above).
If no traits with relevant impls are found, or if multiple such traits are found, the compiler will
throw an error.

== "of" Keyword and Difference from Rust
In Cairo, the `of` keyword is used in impls to specify the concrete trait that is being implemented,
rather than implementing the trait for a specific type, as is done in Rust with the `for` keyword.
The main difference between Cairo and Rust in this context is that Cairo doesn't have a direct
type-to-trait implementation relationship. Instead, Cairo emphasizes implementing the trait
directly, with the concrete trait name specified after the of keyword.
