pub mod multi_component;
mod account;
mod circuit_contract;
pub mod test_contract;
mod new_syntax_test_contract;
mod minimal_contract;
mod hello_starknet;
pub mod erc20;
mod token_bridge;
mod with_erc20;
mod with_ownable;
mod ownable_erc20;
mod upgradable_counter;
mod mintable;
mod storage_accesses;
mod with_ownable_mini;
mod with_erc20_mini;
mod libfuncs_coverage;
