= Contribution guidelines

When contributing to the Cairo repository, please first discuss the change you wish to make via
issue, email, or any other method with the owners of this repository before making a change.

Please note we have a link:https://github.com/starkware-libs/cairo/blob/main/docs/CODE_OF_CONDUCT.md[code of conduct], please follow it in all your
interactions with the project.

== Issues and feature requests

You've found a bug in the source code, a mistake in the documentation or maybe you'd like a new
feature? Take a look at link:https://github.com/starkware-libs/cairo/discussions[GitHub Discussions] to see if it's already being discussed.  You can
help us by link:https://github.com/starkware-libs/cairo/issues[submitting an issue on GitHub].
Before you create an issue, make sure to search
the issue archive - your issue may have already been addressed!

Please try to create bug reports that are:

- _Reproducible._ Include steps to reproduce the problem.
- _Specific._ Include as much detail as possible: which version, what environment, etc.
- _Unique._ Do not duplicate existing opened issues.
- _Scoped to a Single Bug._ One bug per report.

**Even better: Submit a pull request with a fix or new feature!**

== How to submit a pull request

1. Search our repository for open or closed
link:https://github.com/starkware-libs/cairo/pulls[Pull Requests]
that relate to your submission. You don't want to duplicate effort.
2. Fork the project
3. Create your feature branch (`git checkout -b feat/amazing_feature`)
4. Implement your feature
5. Run the code formatter for Rust and Cairo (`scripts/rust_fmt.sh && scripts/cairo_fmt.sh`)
6. Commit your changes (`git commit -m 'feat: Add amazing_feature'`)
7. Push to the branch (`git push origin feat/amazing_feature`)
8. link:https://github.com/starkware-libs/cairo/compare[Open a Pull Request]
