cargo publish --package cairo-lang-utils &&
    cargo publish --package cairo-lang-test-utils &&
    cargo publish --package cairo-lang-casm &&
    cargo publish --package cairo-lang-debug &&
    cargo publish --package cairo-lang-proc-macros &&
    cargo publish --package cairo-lang-eq-solver &&
    cargo publish --package cairo-lang-filesystem &&
    cargo publish --package cairo-lang-diagnostics &&
    cargo publish --package cairo-lang-project &&
    cargo publish --package cairo-lang-sierra &&
    cargo publish --package cairo-lang-sierra-type-size &&
    cargo publish --package cairo-lang-sierra-ap-change &&
    cargo publish --package cairo-lang-sierra-gas &&
    cargo publish --package cairo-lang-sierra-to-casm &&
    cargo publish --package cairo-lang-syntax &&
    cargo publish --package cairo-lang-syntax-codegen &&
    cargo publish --package cairo-lang-parser &&
    cargo publish --package cairo-lang-defs &&
    cargo publish --package cairo-lang-formatter &&
    cargo publish --package cairo-lang-plugins &&
    cargo publish --package cairo-lang-semantic &&
    cargo publish --package cairo-lang-lowering &&
    cargo publish --package cairo-lang-sierra-generator &&
    cargo publish --package cairo-lang-compiler &&
    cargo publish --package cairo-lang-starknet-classes &&
    cargo publish --package cairo-lang-starknet &&
    cargo publish --package cairo-lang-runner &&
    cargo publish --package cairo-lang-test-plugin &&
    cargo publish --package cairo-lang-test-runner &&
    cargo publish --package cairo-lang-language-server &&
    cargo publish --package cairo-compile &&
    cargo publish --package cairo-format &&
    cargo publish --package cairo-language-server &&
    cargo publish --package cairo-run &&
    cargo publish --package cairo-test &&
    cargo publish --package sierra-compile &&
    cargo publish --package starknet-compile &&
    cargo publish --package starknet-sierra-compile
