use std::any::Any;
use std::ops::Deref;
use std::sync::Arc;

use smol_str::SmolStr;
use syntax::node::ast;
use syntax::node::db::SyntaxGroup;
use syntax::node::ids::SyntaxStablePtrId;

/// A trait for mapping plugin generated diagnostics to more readable diagnostics.
pub trait MacroToken: std::fmt::Debug + Sync + Send {
    fn as_any(&self) -> &dyn Any;
    fn eq(&self, other: &dyn MacroToken) -> bool;
}

#[derive(Clone, Debug)]
pub struct DynMacroToken(pub Arc<dyn MacroToken>);
impl DynMacroToken {
    pub fn new<T: MacroToken + 'static>(token: T) -> Self {
        DynMacroToken(Arc::new(token))
    }
}
impl Deref for DynMacroToken {
    type Target = Arc<dyn MacroToken>;

    fn deref(&self) -> &Self::Target {
        &self.0
    }
}
impl PartialEq for DynMacroToken {
    fn eq(&self, that: &DynMacroToken) -> bool {
        MacroToken::eq(&*self.0, &*that.0)
    }
}
impl Eq for DynMacroToken {}

/// Virtual code file generated by a plugin.
pub struct PluginGeneratedFile {
    /// Name for the virtual file. Will appear in diagnostics.
    pub name: SmolStr,
    /// Code content for the file.
    pub content: String,
    /// A diagnostics mapper, to allow more readable diagnostics that originate in plugin generated
    /// virtual files.
    pub token: DynMacroToken,
}

/// Result of plugin code generation.
#[derive(Default)]
pub struct PluginResult {
    /// Filename, content.
    pub code: Option<PluginGeneratedFile>,
    /// Diagnostics.
    pub diagnostics: Vec<PluginDiagnostic>,
}

#[derive(Clone, Debug, Eq, Hash, PartialEq)]
pub struct PluginDiagnostic {
    pub stable_ptr: SyntaxStablePtrId,
    pub message: String,
}

// TOD(spapini): Move to another place.
/// A trait for a macro plugin: external plugin that generates additional code for items.
pub trait MacroPlugin: std::fmt::Debug + Sync + Send {
    /// Generates code for an item. If no code should be generated returns None.
    /// Otherwise, returns (virtual_module_name, module_content), and a virtual submodule
    /// with that name and content should be created.
    fn generate_code(&self, db: &dyn SyntaxGroup, item_ast: ast::Item) -> PluginResult;
}
