= How to contribute

First off, thanks for taking the time to contribute! Contributions are what make the open-source community such an amazing place to learn, inspire, and create. Any contributions you make will benefit everyone else and are **greatly appreciated**.

Please read xref:../../appendices/pages/contribution-guidelines.adoc[our contribution guidelines], and thank you for being
involved!

## Support

- We encourage developers to ask and answer questions on https://stackoverflow.com/questions/tagged/cairo-lang[stackoverflow].
- Contact options listed on link:https://github.com/starkware-libs[this GitHub profile]

## Project assistance

If you want to say **thank you** and/or support active development of Cairo:

- Add a https://github.com/starkware-libs/cairo[GitHub Star] to the project.
- Tweet about your Cairo work.
- Write interesting articles about the project on https://dev.to/[Dev.to], https://medium.com/[Medium] or your
personal blog.

Together, we can make Cairo **better**!

## Authors & contributors

For a full list of all authors and contributors, see link:https://github.com/starkware-libs/cairo/contributors[the contributors page].
