:stem: latexmath

[id="block_structure"]
= Block structure

In StarkNet, the block is defined as a list of transactions and a block header.

[id="block_header"]
== Block header

The following fields define the block header:

[%autowidth]
|===
| Name | Type | Description | Implemented

| `parent_block_hash` | `FieldElement` | The hash of this block's parent | &#10003;
|`block_number` | `Integer` | The number (height) of this block | &#10003;
| `global_state_root` | `FieldElement` | The state xref:../State/starknet-state.adoc#state-commitment[commitment] after this block | &#10003;
|`sequencer_address` | `FieldElement` | The StarkNet address of the sequencer who created this block | &#10003;
| `block_timestamp` | `Timestamp` | The time the sequencer created this block before executing transactions | &#10003;
|`transaction_count` | `Integer` | The number of transactions in a block | &#10003;
| `transaction_commitment` | `FieldElement` | A commitment to the transactions included in the block | &#10003;
|`event_count` | `Integer` | The number of events | &#10003;
| `event_commitment` | `FieldElement` | A commitment to the events produced in this block | &#10003;
| `protocol_version` | `Integer` | The version of the StarkNet protocol used when creating this block |
| `extra data` | `FieldElement` | Extraneous data that might be useful for running transactions |
|===

[NOTE]
====
The commitment fields `event_commitment` and `transaction_commitment` are the roots of a height 64 binary Merkle Patricia tree. The leaf at index stem:[$i$] corresponds to the hash of the stem:[$i'th$] event for `event_commitment` and stem:[$h(transaction \ hash, signature)$] for `invoke transaction_commitment`. For other types of transactions, we use stem:[$h(0,0)$].
====

[id="block_hash"]
== Block hash

The block hash is defined as the Pedersen hash over the header's elements.

[stem]
++++
\begin{aligned}
h(B)=h(&\text{block_number}, \text{ global_state_root}, \text{ sequencer_address}, \text{ block_timestamp}, \\
&\text{transaction_count}, \text{ transaction_commitment}, \text{ event_count},\\
& \text{event_commitment}, 0, 0, \text{ parent_block_hash})
\end{aligned}
++++

Where stem:[$h$] is the xref:../Hashing/hash-functions.adoc#pedersen-hash[Pedersen] hash.

[NOTE]
====
Zeroes inside the hash computation of an object are used as placeholders, to be replaced in the future by meaningful fields.
====