name: Crate Artifacts
on: workflow_dispatch
jobs:
  create_artifacts:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@d23441a48e516b6c34aea4fa41551a30e30af803 # v6
      - uses: dtolnay/rust-toolchain@4cda84d5c5c54efe2404f9d843567869ab1699d4 # stable
      - name: Install musl tools.
        run: sudo apt-get install -y musl-tools
      - name: Build for unknown Linux
        run: ./scripts/release_tar.sh x86_64-unknown-linux-musl
      - name: Archive artifacts
        uses: actions/upload-artifact@ea165f8d65b6e75b540449e92b4886f43607fa02 # v4
        with:
          name: release-x86_64-unknown-linux-musl
          path: target/x86_64-unknown-linux-musl.tar.gz
