name: Tree sitter
on:
  schedule:
    - cron: "0 0 * * *"

jobs:
  test:
    name: Test tree-sitter parser
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
    steps:
      - name: Checkout repository
        uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
      - name: Set up tree-sitter
        uses: tree-sitter/setup-action/cli@49f8c1f20b60102eae8c033bb7c7f6cd056f6086 # v2
      - name: Clone tree-sitter-repo
        run: |-
          git clone https://github.com/starkware-libs/tree-sitter-cairo --single-branch --depth=1 --filter=blob:none
          mv tree-sitter-cairo/** .
      - name: Parse examples
        uses: tree-sitter/parse-action@f44ffa94f802024f27e821a72e6f2f3efc5dd521 # v4
        with:
          files: ./**/*.cairo
          invalid-files: crates/cairo-lang-parser/src/parser_test_data/cairo_test_files/*.cairo

  notify_failed:
    runs-on: ubuntu-latest
    # Do not run on dry_run or success
    if: always() && !(inputs.dry_run) && contains(needs.*.result, 'failure')
    needs: [ test ]
    steps:
      - name: Notifying about Nightly fail!
        uses: slackapi/slack-github-action@dcb1066f776dd043e64d0e8ba94ca15cc7e1875d # v4.0.0
        with:
          webhook: ${{ secrets.SLACK_TREE_SITTER_FAILURE_WEBHOOK }}
          webhook-type: webhook-trigger
          payload: |
            {
              "url": "${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}"
            }
